spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle10gDialect
      